version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9000:9000" # Exposer le port PHP-FPM
        environment:
            - APP_ENV=local
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=test-technique-mdw
            - DB_USERNAME=root
            - DB_PASSWORD=
        depends_on:
            - db
        volumes:
            - .:/var/www/html

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: test-technique-mdw
            MYSQL_ROOT_PASSWORD: "" # Permettre un mot de passe vide pour l'utilisateur root
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Permettre un mot de passe vide pour l'utilisateur root de MySQL
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    web:
        image: caddy:alpine
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - app

volumes:
    db_data:
